### ISSUE TITLE
lru_array

### ISSUE THREAD

**Issue by mmsamiei** [Tabrizian/Cache#1]
hello mr Tabrizian !

how do you do when you have data that in first time updates and other data in same sets change but not updates ? in this case first data remain in cache but another data is going to remove from cache.

thanks a lot 
mmsamiei

**Comment by Tabrizian** [comment]
سلام برادر
نمی‌دونم چه کنم
دارم دیوانه می‌شم

**Comment by mmsamiei** [comment]
این چیه که فرستادی ؟
